name: build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 准备环境
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
      - name: 克隆源码
        uses: actions/checkout@v4
        with:
          repository: LiBwrt/openwrt-6.x
          path: openwrt
      - name: 更新软件
        run: |
          cd openwrt
          ./scripts/feeds update -a && ./scripts/feeds install -a
      - name: 克隆配置
        uses: actions/checkout@v4
        with:
          path: temp
      - name: 更新配置
        run: |
          cd openwrt
          cp ../temp/config ./.config
          make defconfig
      - name: 下载工具
        run: |
          cd openwrt
          make download -j$(nproc)
      - name: 编译固件
        run: |
          cd openwrt
          make V=s -j$(nproc)
